### ISSUE TITLE
mayfly issue - rings of ascension 

### ISSUE THREAD

**Issue by superon** [SFort/MC-SurvivalFlight#4]
just now noticing mayfly:PlayerAbillity problem also with the rings of ascension mod that means flight with a flight ring is disabled with console error:
[14:28:56] [Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:72) ~[f4dfcc6a-1b55-42be-9f41-abdf7226be43.jar:?]
	at net.minecraft.class_3222.handler$cbk000$checkAbilityConsistency(class_3222.java:8187) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3222.method_7355(class_3222.java:1252) ~[intermediary-1.16.5.jar:?]
	at com.focamacho.ringsofascension.item.rings.ItemRingFlight.tick(ItemRingFlight.java:25) ~[RingsOfAscension-1.16.4-1.1.1.jar:?]
	at net.minecraft.class_1661.handler$ebh002$updateItems(class_1661.java:4207) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1661.method_7381(class_1661.java:267) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:563) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2254) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:91) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

thought you should know

survivalflight-1.1.5-1.16

**Comment by superon** [comment]
could "fix" the flight (not the spam though i guess) myself if SF had trinket compat to point to a specific trinket slot... i initially thought just having a flight ring in the inventory could be enough of a fix but i can't find an "in-inventory" option either.

**Comment by SFort** [comment]
ye fscript is still fairly early in development and doesn't have all the options i'd like in-invertory and slot indexing being something i've had planned but not gotten around to yet.

as for the log spam it's PlayerAbilityLib. will add support for when i can (eta one or two days)

**Comment by SFort** [comment]
I'll see what i can do about trinket compatability, but that's gonna take a while longer

**Comment by superon** [comment]
:)
